### ISSUE TITLE
Ask for the username and password to login to HPE hub.

### ISSUE THREAD

**Issue by leafs-cl** [KatherLab/swarm-learning-hpe#56]

**Comment by leafs-cl** [comment]
I meet some errors when running the following command. Could you please provide me with a username and password to login to the HPE hub?
![Uploading Screen Shot 2023-10-08 at 4.57.53 PM.png…]()

**Comment by Ultimate-Storm** [comment]
@leafs-cl hi I just saw your issue. You may use jiefu.zhu@tu-dresden.de as username and hpe as password
